import { StyleSheet } from "react-native"

const styles = StyleSheet.create({
  rectoriaZone: {
    borderColor: "#ef4444",
    borderWidth: 2,
    borderRadius:6,
    width: 30,
    height: 80,
    position: "absolute",
    top: 500,  // posición vertical
    left: 300, // posición horizontal
  },

  // Zona Biblioteca 
  bibliotecaZone: {
    borderColor: "#3b82f6",
    borderWidth: 2,
    borderRadius: 6,
    width: 40,
    height: 60,
    position: "absolute",
    top: 425,
    left: 318,
  },
  // Zona Quimica 
  quimicaZone: {
    borderColor: "#06a374ff",
    borderWidth: 2,
    borderRadius: 6,
    width: 147,
    height: 20,
    position: "absolute",
    top: 352,
    left: 230,
    transform: [{ rotate: "31deg"}],
  },
  // Zona matute 
  matuteZone: {
    borderColor: "#b8da0dff",
    borderWidth: 2,
    borderRadius: 6,
    width: 25,
    height: 22,
    position: "absolute",
    top: 288,
    left: 345,
    transform: [{ rotate: "90deg"}],
  },
    // Zona Antonio 
  antonioZone: {
    borderColor: "#b58a08ff",
    borderWidth: 2,
    borderRadius: 6,
    width: 17.5,
    height: 17.5,
    position: "absolute",
    top: 228,
    left: 321,
    transform: [{ rotate: "125deg"}],
  },
      // Zona Antonio 
  moduloYZone: {
    borderColor: "#803b06ff",
    borderWidth: 2,
    borderRadius: 6,
    width: 17.5,
    height: 17.5,
    position: "absolute",
    top: 175,
    left: 285,
    transform: [{ rotate: "125deg"}],
  },
  moduloVZone: {
    borderColor: "#803b06ff",
    borderWidth: 2,
    borderRadius: 6,
    width: 25,
    height: 45,
    position: "absolute",
    top: 165,
    left: 345,
    transform: [{ rotate: "130deg"}],
  },
  moduloUZone: {
    borderColor: "#3f1092ff",
    borderWidth: 2,
    borderRadius: 6,
    width: 12.5,
    height: 35,
    position: "absolute",
    top: 215,
    left: 375,
    transform: [{ rotate: "130deg"}],
  },
  moduloQZone: {
    borderColor: "#08cecbff",
    borderWidth: 2,
    borderRadius: 6,
    width: 10,
    height: 38,
    position: "absolute",
    top: 260,
    left: 385,
    transform: [{ rotate: "130deg"}],
  },
  moduloNZone: {
    borderColor: "#c4071aff",
    borderWidth: 2,
    borderRadius: 6,
    width: 27,
    height: 30,
    position: "absolute",
    top: 255,
    left: 320,
    transform: [{ rotate: "130deg"}],
  },
  moduloKZone: {
    borderColor: "#3b78aaff",
    borderWidth: 2,
    borderRadius: 4,
    width: 7,
    height: 40,
    position: "absolute",
    top: 275,
    left: 327,
    transform: [{ rotate: "130deg"}],
  },
  moduloPZone: {
    borderColor: "#e6bc15ff",
    borderWidth: 2,
    borderRadius: 6,
    width: 12.5,
    height: 35,
    position: "absolute",
    top: 257,
    left: 364,
    transform: [{ rotate: "130deg"}],
  },
  moduloFZone: {
    borderColor: "#25c585ff",
    borderWidth: 2,
    borderRadius: 4,
    width: 15.5,
    height: 35,
    position: "absolute",
    top: 329.5,
    left: 325,
    transform: [{ rotate: "185deg"}],
  },
  moduloRZone: {
    borderColor: "#670c65ff",
    borderWidth: 2,
    borderRadius: 3.5,
    width: 12.5,
    height: 18.5,
    position: "absolute",
    top: 250,
    left: 365,
    transform: [{ rotate: "125deg"}],
  },
  moduloTZone: {
    borderColor: "#d3685aff",
    borderWidth: 2,
    borderRadius: 3.5,
    width: 10,
    height: 25,
    position: "absolute",
    top: 233,
    left: 375,
    transform: [{ rotate: "130deg"}],
  },
  moduloXZone: {
    borderColor: "#54710bff",
    borderWidth: 2,
    borderRadius: 3.5,
    width: 20,
    height: 30,
    position: "absolute",
    top: 140,
    left: 310,
    transform: [{ rotate: "130deg"}],
  },
  moduloAlfaOmegaZone: {
    borderColor: "#0571c5ff",
    borderWidth: 2,
    borderRadius: 6,
    width: 24,
    height: 20,
    position: "absolute",
    top: 325,
    left: 355,
    transform: [{ rotate: "115deg"}],
  },
  titanicZone: {
    borderColor: "#073e68ff",
    borderWidth: 2,
    borderRadius: 4,
    width: 17,
    height: 17,
    position: "absolute",
    top: 255,
    left: 390,
    transform: [{ rotate: "115deg"}],
  },
  // Zona Quimica 
  LabquimicaZone: {
    borderColor: "#1d982eff",
    borderWidth: 2,
    borderRadius: 6,
    width: 20,
    height: 20,
    position: "absolute",
    top: 365,
    left: 255,
    transform: [{ rotate: "31deg"}],
  },
  LabindustrialZone: {
    borderColor: "#065d5eff",
    borderWidth: 2,
    borderRadius: 6,
    width: 17,
    height: 15,
    position: "absolute",
    top: 215,
    left: 330,
    transform: [{ rotate: "31deg"}],
  },
  CorredocomidaZone: {
    borderColor: "#a5840cff",
    borderWidth: 2,
    borderRadius: 6,
    width: 25,
    height: 45,
    position: "absolute",
    top: 120,
    left: 335,
    transform: [{ rotate: "15deg"}],
  },
});

export const zonas =[
    {id: "rectoria", style: styles.rectoriaZone},
    {id: "bibloteca", style: styles.bibliotecaZone},
    {id: "quimica", style: styles.quimicaZone},
    {id: "moduloY", style: styles.moduloYZone},
    {id: "moduloV", style: styles.moduloVZone},
    {id: "moduloU", style: styles.moduloUZone},
    {id: "moduloQ", style: styles.moduloQZone},
    {id: "moduloN", style: styles.moduloNZone},
    {id: "moduloK", style: styles.moduloKZone},
    {id: "moduloP", style: styles.moduloPZone},
    {id: "moduloF", style: styles.moduloFZone},
    {id: "moduloR", style: styles.moduloRZone},
    {id: "moduloT", style: styles.moduloTZone},
    {id: "moduloX", style: styles.moduloXZone},
    {id: "modulosAlfaOmega", style: styles.moduloAlfaOmegaZone},
    {id: "matute", style: styles.matuteZone},
    {id: "antonio", style: styles.antonioZone},
    {id: "labTitanic", style: styles.titanicZone},
    {id: "labQuimica", style: styles.LabquimicaZone},
    {id: "labIndustrial", style: styles.LabindustrialZone},
    {id: "corredorComida", style: styles.CorredocomidaZone},
]